site_name: Airavata Operations Manual
docs_dir: .

pages:
- Home: index.md
- Installations: Installation.md
- Airavata & PGA Configuration: Gateway-Configurations.md
- FAQ: FAQ.md
- User Profiles: User-Profiles.md
- Applications: Application-CookBook.md
- Airavata API: AiravataApi.md
- Contact Us: Contact-Us.md

theme: mkdocs
