site_name: Airavata Operations Manual
docs_dir: .
pages:
- Home: index.md
- Installations: Installation.md
- User Profiles: User-Profiles.md
- PGA Gateway: Gateway-Configurations.md
- Applications: Application-CookBook.md
- Pending: Pending.md

theme: readthedocs
